name: clip_pix
description: Clipboard-driven image collection tool for Windows desktop.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_hooks: ^0.20.5
  flutter_state_notifier: ^0.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  watcher: ^1.1.0
  win32: ^5.5.4
  window_manager: ^0.3.9
  screen_retriever: ^0.1.9
  http: ^1.2.2
  logging: ^1.2.0
  path: ^1.9.0
  flutter_staggered_grid_view: ^0.7.0
  image: ^4.2.0
  crypto: ^3.0.6
  file_selector: ^1.0.3
  state_notifier: ^0.7.2
  audioplayers: ^6.1.0
  path_provider: ^2.1.0
  pdfx: ^2.6.0
  showcaseview: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  mocktail: ^1.0.3
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/sounds/
